# Site settings
title: CADI Anleitung # the title of your site
description: Diese Dokumentation beschreibt, wie verschiedene Komponenten auf der Ihrer Website eingebunden  werden können. Hier finden Sie Schritt-für-Schritt-Anleitungen und Beispiele für die Einbindung und Einrichtung von Komponenten (Buchungsmaske, Termintabelle und Product Finder).
#url: https://Leon-1207.github.io # the base hostname & protocol for your site

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# plugins:
#  - jekyll-feed # generates an Atom feed of your posts

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  # tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: true

# For copy button on code
enable_copy_code_button: true